// FILE: src/lib/lafLocations.ts
export const LAF_LOCATIONS = [
  // --- Orange County ---
  "Aliso Viejo",
  "Anaheim - Euclid",
  "Anaheim Hills",
  "Brea",
  "Cypress",
  "Fountain Valley",
  "Fullerton",
  "Garden Grove",
  "Huntington Beach - Beach Blvd",
  "Huntington Beach - Warner",
  "Irvine - Culver",
  "Irvine - Jamboree",
  "Irvine - Marketplace",
  "Laguna Hills",
  "Laguna Niguel",
  "Lake Forest",
  "Mission Viejo",
  "Newport Beach",
  "Orange - Tustin Ave",
  "Placentia",
  "Rancho Santa Margarita",
  "San Clemente",
  "San Juan Capistrano",
  "Santa Ana",
  "Tustin",
  "Yorba Linda",

  // --- LA County (sample; extend as needed) ---
  "Burbank",
  "Culver City",
  "Downey",
  "Glendale",
  "Hawthorne",
  "Hollywood",
  "Long Beach - Downtown",
  "Long Beach - Spring",
  "Los Angeles - South Gate",
  "Manhattan Beach",
  "Pasadena",
  "Santa Monica",
  "Sherman Oaks",
  "Torrance",
  "West Hollywood",

  // Catch-all
  "Unknown / Other",
];
